mqtt:
  host: 192.168.1.89
  user: shelly
  password: ydjZ8YqVV6uG9Zpt

database:
  path: /db/frigate.db

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
    objects:
      - person
      - bicycle
      - car
      - motorcycle
      - car

go2rtc:
  streams:
    oprit:
      - rtsp://admin:Ae9FGhgfnCEFYUxM@192.168.1.141:554/Streaming/Channels/101/?transportmode=unicast.sdp
    oprit_sub:
      - rtsp://admin:Ae9FGhgfnCEFYUxM@192.168.1.141:554/Streaming/Channels/102/?transportmode=unicast.sdp
    tuinkamer:
      - rtsp://admin:Ae9FGhgfnCEFYUxM@192.168.1.157:554/Streaming/Channels/101/?transportmode=unicast.sdp
    tuinkamer_sub:
      - rtsp://admin:Ae9FGhgfnCEFYUxM@192.168.1.157:554/Streaming/Channels/102/?transportmode=unicast.sdp
  webrtc:
    candidates:
      - 192.168.1.192:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 640
  height: 480
  fps: 6
  enabled: True
  max_disappeared: 30
  stationary:
    interval: 5
    threshold: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - car
    - boat
    - bird
    - cat
    - dog

motion:
  mask:
    - 0,33,206,31,208,0,0,0,0,0

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

live:
  height: 1440
  quality: 8

cameras:
  oprit:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/oprit
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/oprit_sub
          roles:
            - detect
    zones:
      heleOprit:
        coordinates: 477,480,491,165,344,148,67,480
        objects:
          - person
          - bicycle
          - car
          - car
    record:
      events:
        required_zones:
          - heleOprit
  tuinkamer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tuinkamer
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuinkamer_sub
          roles:
            - detect
    zones:
      heleTuinKamer:
        coordinates: 640,480,640,83,450,50,0,112,0,480
    record:
      events:
        required_zones:
          - heleTuinkamer