---
# Installs the kubernetes components for the control plane and the workers
# This script assumes docker is already installed using install_docker.yml
- hosts: kubernetes_controlplane.local
  become: yes
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: "qemu-guest-agent"
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - qemu-guest-agent
        - kubeadm
        - kubelet
        - kubectl

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: yes

    - name: Set up kubectl for the current user
      command: "{{ item }}"
      with_items:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: Install Calico network plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: "'calico' in kubeadm_output.stdout"

- hosts: kubernetes-worker1.local kubernetes-worker2.local
  become: yes
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: "qemu-guest-agent"
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Join worker nodes to the cluster
      command: "{{ hostvars['kubernetes_controlplane']['kubeadm_output']['stdout_lines'][0] }}"
      when: "'kubeadm join' in hostvars['kubernetes_controlplane']['kubeadm_output']['stdout']"